version: '3'

services:
   hello-svc:
     image: hello
     restart: always
     ports:
       - "5000"

   world-svc:
     image: world
     restart: always
     ports:
       - "5000"

   helloword:
     depends_on:
       - hello-svc
       - world-svc 
     image: helloworld
     ports:
       - "30000:5000"
     restart: always
