Kubernetes:
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tomcat
  name: tomcat
  namespace: default
spec:
  type: "LoadBalancer"
  ports:
  - port: 8080
    targetPort: 8080
    protocol: "TCP"
    nodePort: 30001
  selector:
    name: tomcat-server
